name: Project RXY

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,47,48,49,50,51,52,53,54,55,56,57,58,59 6-7 * * *"

jobs:
  project_rxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0  
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify RXY
        run: |
          cat > RXY
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > RXY
          
      - name: Commit changes
        run: |
          git config --local user.email "theiiisociety.help@gmail.com"
          git config --local user.name "1rb"
          git add -A
          
          arr[0]="you know what... coding isn't for me"
          arr[1]="FINALLY. this should work"
          arr[2]="if you see this... im sorry..."
          arr[3]="yep. i give up"
          arr[4]="SEND HELP PLEASE :C"
          arr[5]="fixed... i think"
          arr[6]="you better work now."
          arr[7]="I regret being born"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
