name: Project RXY

on:
  push:
    branches:
      - master
      
  schedule:
  - cron: "20/10 * * * *"

jobs:
  project_rxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0  
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify README.md
        run: |
          response=$(curl https://api-inference.huggingface.co/models/bigscience/bloom \
            -X POST \
            -d '{"inputs": "Can you please explain the functionality of algorithms in computer science"}' \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.HUGGINGFACE }}")
          echo "$response" > README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "theiiisociety.help@gmail.com"
          git config --local user.name "1rb"
          git add -A
          
            commit_message=$(curl -s https://whatthecommit.com/index.txt)
            git commit -m "$commit_message"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
