name: Project RXY

on:
  push:
    branches:
      - master
      
  schedule:
  - cron: "20/10 * * * *"

jobs:
  project_rxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0  
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify README.md
        run: |
          cat > README.md <<EOF
          # rxy
          rxy is a tool for solving complex problems in a efficient manner. It utilizes cutting-edge techniques and algorithms to deliver accurate and reliable results.
          
          Last Edited: $(date '+%Y-%m-%d')
          
          ## Features
          - Divide and conquer: rxy uses the divide and conquer approach to break complex problems down into smaller, more manageable pieces and solve them individually
          - Dynamic programming: rxy uses dynamic programming to store the solutions to subproblems in a table, enabling efficient reuse of these solutions.
          - Graph search: rxy includes algorithms for traversing graph data structures in order to find solutions to problems.
          
          ## Installation
          To install rxy, clone the repository and run `npm install`:
          
          
          git clone https://github.com/1RB/rxy.git
          cd rxy
          npm install
          
          
          ## Usage
          To use rxy, require it in your project and call the desired function:
          
          `javascript
          const rxy = require('rxy');
          console.log(rxy.findMax([1, 2, 3, 4, 5]));  // prints 5
          console.log(rxy.knapsack([[5, 3], [4, 2], [6, 4], [3, 1]], 6));  // prints 9
          for (const path of rxy.dfs({1: [2, 3], 2: [4, 5], 3: [5]}, 1, 5)) {
          console.log(path);  // prints [1, 2, 5] and [1, 3, 5]
          }
          `
          
          ## Contributing
          If you are interested in contributing to the project, please see the [contributing guidelines](CONTRIBUTING.md).
          
          ## License
          rxy is released under the [MIT License](LICENSE).

          EOF

          
      - name: Commit changes
        run: |
          git config --local user.email "theiiisociety.help@gmail.com"
          git config --local user.name "1rb"
          git add -A
          
          arr[0]="you know what... coding isn't for me"
          arr[1]="FINALLY. this should work"
          arr[2]="if you see this... im sorry..."
          arr[3]="yep. i give up"
          arr[4]="SEND HELP PLEASE :C"
          arr[5]="fixed... i think"
          arr[6]="you better work now."
          arr[7]="I regret being born"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
