name: Project RXY

on:
  push:
    branches:
      - master
      
  schedule:
      - cron: "*/30 14-20 * * *"
    # - cron: "21/21,9-21/9 14-20,1-3 * * 1" # monday
    # - cron: "14/23 14-20 * * 2" # tuesday
    # - cron: "22,23,24 15 * * 3" # wednesday
    # - cron: "3,16,22,40,41,42 14 * * 4" # thursday
    # - cron: "3,4-36/7,37-50/3 14-23,0-3 * * 5" # friday
    # - cron: "*/16 10-12 * * 6" # saturday and sunday
    # - cron: "*/16 10-12 * * 7" # saturday and sunday
        

jobs:
  project_rxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0  
        with:
         persist-credentials: false
         fetch-depth: 0
      
      - name: Random Sleep
        run: |
           delay=$[ ( $RANDOM % 25200 )  ]s
           echo "Delaying for $delay seconds"
           sleep $delay

      - name: Modify files
        run: |

          # response=$(curl https://api-inference.huggingface.co/models/bigscience/bloom \
          #   -X POST \
          #   -d '{"inputs": ""}' \
          #   -H 'Content-Type: application/json' \
          #   -H "Authorization: Bearer ${{ secrets.HUGGINGFACE }}")
          #   echo "$response" >> README.md
                   
            last_number=$(tail -n 1 "src/Data/numbers.txt")
            new_number=$((last_number + 1))
            echo "$new_number" >> "src/Data/numbers.txt"

      - name: Random Sleep 2
        run: |
           delay=$[ ( $RANDOM % 86400 )  ]s
           echo "Delaying for $delay seconds"
           sleep $delay

      - name: Commit changes
        run: |
          git config --local user.email "theiiisociety.help@gmail.com"
          git config --local user.name "1rb"
          git add -A
          
            commit_message=$(curl -s https://whatthecommit.com/index.txt)
            git commit -m "$commit_message"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
